version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13.4-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
